language: node_js
node_js:
  - 18
dist: focal  # Specify Ubuntu Focal (20.04) distribution
install:
  - npm i -g markbind-cli
script: markbind build
deploy:
  provider: script
  script: markbind deploy --ci
  skip_cleanup: true
  on:
    branch: main