name: Deploy MarkBind Site
on:
  push:
    branches: main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: gerteck/markbind-action@branch-upgrade-node-v20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}